### ISSUE TITLE
More code comments please

### ISSUE THREAD

**Issue by planemad** [mapbox/osm-query#12] opened 2015-09-09 12:24 UTC
Was going through app.js and took some time to figure out as there was a lack of comments (0 to be precise). While most of it is self explanatory code there are some lines that could use a comment to better understand whats going on to someone looking at it for the first time like [this line](https://github.com/mapbox/osm-query/blob/master/js/app.js#L10).

**Add comments**
- [ ] @geohacker 
- [ ] @ramyaragupathy

**Comment by geohacker** [comment] 2015-09-17 09:07
Duplicate of #7

**Closed as completed by geohacker** 2015-09-17 09:07 UTC
